# Generated by Django 4.1.5 on 2023-02-05 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('NEBULOSA', 'Nebulosa'), ('PLANETA', 'Planeta'), ('ESTRELA', 'Estrela'), ('GALÁXIA', 'Galáxia')], default='', max_length=100),
        ),
    ]
